repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.9
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes"]
        files: ^src/
      - id: ruff-format
        files: ^src/

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uv run ty check
        language: system
        pass_filenames: false
        files: ^src/
