repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.5  # uv version
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: testing
        name: testing
        entry: pytest
        args: [ tests ]
        language: python
        pass_filenames: false

      - id: linting
        name: linting
        entry: ruff
        args: [ check, src, --fix ]
        language: python
        pass_filenames: false

      - id: formatting
        name: formatting
        entry: ruff
        args: [ format, src ]
        language: python
        pass_filenames: false

      - id: typechecking
        name: typechecking
        entry: mypy
        args: [ src, --ignore-missing-imports ]
        language: python
        pass_filenames: false
